use std::fmt::Write as _;
use std::fs::{self, OpenOptions};
use std::io::Write as _;
use std::path::{Path, PathBuf};

use sddk_domain::{GateTypeDef, Requirement, StateRef, WorkflowManifest};
use thiserror::Error;

/// Canonical generated workflow documentation path, relative to the repository root.
pub const GENERATED_WORKFLOW_DOC: &str = "docs/generated/workflow.md";
const WORKFLOW_MANIFEST: &str = "workflow/workflow.yaml";

/// Outcome of generating or checking workflow documentation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GenerationStatus {
    /// Existing generated documentation matches the canonical rendering.
    Current,
    /// Generated documentation was replaced atomically.
    Written,
    /// Check mode found missing or stale generated documentation.
    Stale,
}

/// Failures while loading, rendering, or writing generated documentation.
#[derive(Debug, Error)]
pub enum GenerationError {
    /// The canonical workflow could not be loaded through the engine.
    #[error("failed to load canonical workflow: {0}")]
    Workflow(#[from] sddk_engine::WorkflowLoadError),
    /// A filesystem operation failed.
    #[error("filesystem operation failed for {path}: {source}")]
    Io {
        /// Affected path.
        path: PathBuf,
        /// Underlying I/O error.
        source: std::io::Error,
    },
}

/// Deterministically renders workflow documentation and either checks or writes it.
pub fn generate_workflow_docs(
    root: impl AsRef<Path>,
    check: bool,
) -> Result<GenerationStatus, GenerationError> {
    let root = root.as_ref();
    let manifest = sddk_engine::load_workflow_path(root.join(WORKFLOW_MANIFEST))?;
    let rendered = render_workflow_docs(&manifest);
    let destination = root.join(GENERATED_WORKFLOW_DOC);
    sync_generated_file(&destination, &rendered, check).map_err(|source| GenerationError::Io {
        path: destination,
        source,
    })
}

/// Like `generate_workflow_docs`, but writes to `destination_dir` (XDG) instead
/// of the repo — non-intrusive policy (ADR-0011). The workflow manifest is
/// resolved from the embedded canonical when the repo has none.
pub(crate) fn generate_workflow_docs_to(
    root: impl AsRef<Path>,
    destination_dir: impl AsRef<Path>,
    check: bool,
) -> Result<GenerationStatus, GenerationError> {
    let root = root.as_ref();
    let manifest = match sddk_engine::load_workflow_path(root.join(WORKFLOW_MANIFEST)) {
        Ok(manifest) => manifest,
        Err(error) if matches!(&error, sddk_engine::WorkflowLoadError::Io { .. }) => {
            sddk_engine::load_workflow_str(crate::CANONICAL_WORKFLOW)?
        }
        Err(error) => return Err(error.into()),
    };
    let rendered = render_workflow_docs(&manifest);
    let destination = destination_dir.as_ref().join(GENERATED_WORKFLOW_DOC);
    sync_generated_file(&destination, &rendered, check).map_err(|source| GenerationError::Io {
        path: destination,
        source,
    })
}

pub(crate) fn render_workflow_docs(manifest: &WorkflowManifest) -> String {
    let mut output = String::new();
    writeln!(output, "# Generated Workflow Reference").expect("writing to a string cannot fail");
    writeln!(output).expect("writing to a string cannot fail");
    writeln!(
        output,
        "> Generated by `sddk generate docs` from `{WORKFLOW_MANIFEST}`. Do not edit manually."
    )
    .expect("writing to a string cannot fail");
    writeln!(output).expect("writing to a string cannot fail");

    writeln!(output, "## Workflow Metadata\n").expect("writing to a string cannot fail");
    writeln!(output, "| Field | Value |").expect("writing to a string cannot fail");
    writeln!(output, "| --- | --- |").expect("writing to a string cannot fail");
    writeln!(output, "| ID | `{}` |", markdown(&manifest.workflow.id))
        .expect("writing to a string cannot fail");
    writeln!(
        output,
        "| Version | `{}` |",
        markdown(&manifest.workflow.version)
    )
    .expect("writing to a string cannot fail");
    writeln!(output, "| Schema version | `{}` |", manifest.schema_version)
        .expect("writing to a string cannot fail");
    writeln!(
        output,
        "| Description | {} |",
        markdown(&manifest.workflow.description)
    )
    .expect("writing to a string cannot fail");
    writeln!(output).expect("writing to a string cannot fail");

    writeln!(output, "## Statuses\n").expect("writing to a string cannot fail");
    writeln!(output, "| Order | Status |").expect("writing to a string cannot fail");
    writeln!(output, "| ---: | --- |").expect("writing to a string cannot fail");
    for (index, status) in manifest.statuses.iter().enumerate() {
        writeln!(output, "| {} | `{}` |", index + 1, wire(status))
            .expect("writing to a string cannot fail");
    }
    writeln!(output).expect("writing to a string cannot fail");

    writeln!(output, "## Phases\n").expect("writing to a string cannot fail");
    writeln!(output, "| Order | Phase |").expect("writing to a string cannot fail");
    writeln!(output, "| ---: | --- |").expect("writing to a string cannot fail");
    for (index, phase) in manifest.phases.iter().enumerate() {
        writeln!(output, "| {} | `{}` |", index + 1, wire(phase))
            .expect("writing to a string cannot fail");
    }
    writeln!(output).expect("writing to a string cannot fail");

    writeln!(output, "## Paths\n").expect("writing to a string cannot fail");
    writeln!(
        output,
        "| Path | Debt verification | Phase sequence | Description |"
    )
    .expect("writing to a string cannot fail");
    writeln!(output, "| --- | --- | --- | --- |").expect("writing to a string cannot fail");
    let mut paths = manifest.paths.iter().collect::<Vec<_>>();
    paths.sort_by_key(|(name, _)| *name);
    for (name, path) in paths {
        writeln!(
            output,
            "| `{}` | `{}` | {} | {} |",
            markdown(name),
            markdown(&path.debt_verification),
            path.phases
                .iter()
                .map(|phase| format!("`{}`", markdown(phase)))
                .collect::<Vec<_>>()
                .join(" → "),
            markdown(&path.description)
        )
        .expect("writing to a string cannot fail");
    }
    writeln!(output).expect("writing to a string cannot fail");

    writeln!(output, "## Transitions\n").expect("writing to a string cannot fail");
    writeln!(
        output,
        "| ID | Paths | From | To | Requirements | Produces | On failure |"
    )
    .expect("writing to a string cannot fail");
    writeln!(output, "| --- | --- | --- | --- | --- | --- | --- |")
        .expect("writing to a string cannot fail");
    for transition in &manifest.transitions {
        let requirements = transition
            .requires
            .iter()
            .map(format_requirement)
            .collect::<Vec<_>>()
            .join("<br>");
        let produces = code_list(&transition.produces);
        writeln!(
            output,
            "| `{}` | {} | {} | {} | {} | {} | {} |",
            markdown(&transition.id),
            empty_dash(code_list(&transition.paths)),
            transition
                .from
                .as_ref()
                .map_or_else(|| "_creation_".to_owned(), format_state),
            format_state(&transition.to),
            empty_dash(requirements),
            empty_dash(produces),
            transition
                .on_failure
                .as_ref()
                .map_or_else(|| "—".to_owned(), format_state)
        )
        .expect("writing to a string cannot fail");
    }
    writeln!(output).expect("writing to a string cannot fail");

    writeln!(output, "## Artifacts\n").expect("writing to a string cannot fail");
    writeln!(
        output,
        "| Artifact | Producer | Consumers | Required | Terminal | Description |"
    )
    .expect("writing to a string cannot fail");
    writeln!(output, "| --- | --- | --- | --- | --- | --- |")
        .expect("writing to a string cannot fail");
    let mut artifacts = manifest.artifacts.iter().collect::<Vec<_>>();
    artifacts.sort_by_key(|(name, _)| *name);
    for (name, artifact) in artifacts {
        writeln!(
            output,
            "| `{}` | `{}` | {} | {} | {} | {} |",
            markdown(name),
            markdown(&artifact.producer),
            empty_dash(code_list(&artifact.consumers)),
            if artifact.required { "yes" } else { "no" },
            if artifact.terminal { "yes" } else { "no" },
            artifact
                .description
                .as_deref()
                .map_or("—".to_owned(), markdown)
        )
        .expect("writing to a string cannot fail");
    }
    writeln!(output).expect("writing to a string cannot fail");

    writeln!(output, "## Gates\n").expect("writing to a string cannot fail");
    writeln!(output, "| Gate | Type | Description |").expect("writing to a string cannot fail");
    writeln!(output, "| --- | --- | --- |").expect("writing to a string cannot fail");
    let mut gates = manifest.gates.iter().collect::<Vec<_>>();
    gates.sort_by_key(|(name, _)| *name);
    for (name, gate) in gates {
        writeln!(
            output,
            "| `{}` | `{}` | {} |",
            markdown(name),
            gate.gate_type.as_ref().map_or("unspecified", gate_type),
            gate.description.as_deref().map_or("—".to_owned(), markdown)
        )
        .expect("writing to a string cannot fail");
    }
    writeln!(output).expect("writing to a string cannot fail");

    writeln!(output, "## State Diagram\n").expect("writing to a string cannot fail");
    writeln!(output, "```mermaid").expect("writing to a string cannot fail");
    writeln!(output, "stateDiagram-v2").expect("writing to a string cannot fail");
    for transition in &manifest.transitions {
        let from = transition
            .from
            .as_ref()
            .map_or_else(|| "[*]".to_owned(), mermaid_state);
        writeln!(
            output,
            "    {} --> {}: {}",
            from,
            mermaid_state(&transition.to),
            transition.id
        )
        .expect("writing to a string cannot fail");
        if let Some(on_failure) = &transition.on_failure {
            writeln!(
                output,
                "    {} --> {}: {} (failure)",
                from,
                mermaid_state(on_failure),
                transition.id
            )
            .expect("writing to a string cannot fail");
        }
    }
    writeln!(output, "```").expect("writing to a string cannot fail");
    output
}

pub(crate) fn sync_generated_file(
    destination: &Path,
    rendered: &str,
    check: bool,
) -> Result<GenerationStatus, std::io::Error> {
    if check {
        return Ok(match fs::read_to_string(destination) {
            Ok(existing) if existing == rendered => GenerationStatus::Current,
            Ok(_) | Err(_) => GenerationStatus::Stale,
        });
    }

    atomic_write(destination, rendered.as_bytes())?;
    Ok(GenerationStatus::Written)
}

fn atomic_write(destination: &Path, bytes: &[u8]) -> Result<(), std::io::Error> {
    let parent = destination.parent().unwrap_or_else(|| Path::new("."));
    fs::create_dir_all(parent)?;

    let file_name = destination
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("workflow.md");
    let mut last_error = None;
    for attempt in 0..100 {
        let temporary = parent.join(format!(".{file_name}.tmp-{}-{attempt}", std::process::id()));
        match OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temporary)
        {
            Ok(mut file) => {
                let result = (|| {
                    file.write_all(bytes)?;
                    file.sync_all()?;
                    drop(file);
                    fs::rename(&temporary, destination)
                })();
                if let Err(source) = result {
                    let _ = fs::remove_file(&temporary);
                    return Err(source);
                }
                return Ok(());
            }
            Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => {
                last_error = Some(error);
            }
            Err(source) => return Err(source),
        }
    }

    Err(last_error.unwrap_or_else(|| std::io::Error::other("no temporary path available")))
}

fn format_requirement(requirement: &Requirement) -> String {
    match requirement {
        Requirement::Simple(name) => format!("`{}`", markdown(name)),
        Requirement::Structured { kind, name } => {
            format!("`{}:{}`", markdown(kind), markdown(name))
        }
    }
}

fn format_state(state: &StateRef) -> String {
    match state.phase {
        Some(phase) => format!("`{}/{}`", wire(&state.status), wire(&phase)),
        None => format!("`{}/*`", wire(&state.status)),
    }
}

fn mermaid_state(state: &StateRef) -> String {
    match state.phase {
        Some(phase) => format!("{}_{}", wire(&state.status), wire(&phase)),
        None => format!("{}_any", wire(&state.status)),
    }
}

fn gate_type(gate_type: &GateTypeDef) -> &str {
    match gate_type {
        GateTypeDef::Binary {} => "binary",
        GateTypeDef::Percentage { .. } => "percentage",
        GateTypeDef::Count { .. } => "count",
        GateTypeDef::String(value) => value,
    }
}

fn code_list(values: &[String]) -> String {
    values
        .iter()
        .map(|value| format!("`{}`", markdown(value)))
        .collect::<Vec<_>>()
        .join("<br>")
}

fn empty_dash(value: String) -> String {
    if value.is_empty() {
        "—".to_owned()
    } else {
        value
    }
}

fn markdown(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

fn wire<T: serde::Serialize>(value: &T) -> String {
    serde_json::to_value(value)
        .expect("workflow enums are serializable")
        .as_str()
        .expect("workflow enums serialize as strings")
        .to_owned()
}
