use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use thiserror::Error;
use walkdir::WalkDir;

use crate::docs::{GenerationStatus, sync_generated_file};

/// Canonical generated repository inventory path, relative to the repository root.
pub const GENERATED_INVENTORY_DOC: &str = "docs/generated/inventory.md";

/// Failures while collecting or writing the generated repository inventory.
#[derive(Debug, Error)]
pub enum InventoryError {
    /// A repository path is not valid UTF-8.
    #[error("repository path is not valid UTF-8: {0:?}")]
    NonUtf8Path(PathBuf),
    /// Walking a repository directory failed.
    #[error("failed to scan repository inventory below {path}: {source}")]
    Walk {
        /// Directory being scanned.
        path: PathBuf,
        /// Underlying traversal error.
        source: walkdir::Error,
    },
    /// A filesystem operation failed.
    #[error("filesystem operation failed for {path}: {source}")]
    Io {
        /// Affected path.
        path: PathBuf,
        /// Underlying I/O error.
        source: std::io::Error,
    },
}

/// Deterministically renders the agent and skill inventory and either checks or writes it.
pub fn generate_inventory(
    root: impl AsRef<Path>,
    check: bool,
) -> Result<GenerationStatus, InventoryError> {
    let root = root.as_ref();
    let rendered = render_inventory(root)?;
    let destination = root.join(GENERATED_INVENTORY_DOC);
    sync_generated_file(&destination, &rendered, check).map_err(|source| InventoryError::Io {
        path: destination,
        source,
    })
}

/// Like `generate_inventory`, but writes to `destination_dir` (XDG) instead of
/// the repo — non-intrusive policy (ADR-0011). The inventory is rendered from
/// the repo root but stored outside it.
pub(crate) fn generate_inventory_to(
    root: impl AsRef<Path>,
    destination_dir: impl AsRef<Path>,
    check: bool,
) -> Result<GenerationStatus, InventoryError> {
    let root = root.as_ref();
    let rendered = render_inventory(root)?;
    let destination = destination_dir.as_ref().join(GENERATED_INVENTORY_DOC);
    sync_generated_file(&destination, &rendered, check).map_err(|source| InventoryError::Io {
        path: destination,
        source,
    })
}

pub(crate) fn render_inventory(root: &Path) -> Result<String, InventoryError> {
    let agents = collect_paths(root, "agents", |path| {
        path.extension().and_then(|extension| extension.to_str()) == Some("md")
    })?;
    let skills = collect_paths(root, "skills", |path| {
        path.file_name().and_then(|name| name.to_str()) == Some("SKILL.md")
    })?;

    let mut output = String::new();
    writeln!(output, "# Generated Repository Inventory").expect("writing to a string cannot fail");
    writeln!(output).expect("writing to a string cannot fail");
    writeln!(
        output,
        "> Generated by `sddk generate inventory`. Do not edit manually."
    )
    .expect("writing to a string cannot fail");
    writeln!(output).expect("writing to a string cannot fail");
    writeln!(output, "## Summary\n").expect("writing to a string cannot fail");
    writeln!(output, "| Type | Count |").expect("writing to a string cannot fail");
    writeln!(output, "| --- | ---: |").expect("writing to a string cannot fail");
    writeln!(output, "| Agents | {} |", agents.len()).expect("writing to a string cannot fail");
    writeln!(output, "| Skills | {} |", skills.len()).expect("writing to a string cannot fail");
    writeln!(output).expect("writing to a string cannot fail");
    render_paths(&mut output, "Agents", &agents);
    render_paths(&mut output, "Skills", &skills);
    output.pop();
    Ok(output)
}

fn collect_paths(
    root: &Path,
    directory: &str,
    include: impl Fn(&Path) -> bool,
) -> Result<Vec<String>, InventoryError> {
    let base = root.join(directory);
    if !base.exists() {
        return Ok(Vec::new());
    }

    let mut paths = Vec::new();
    for entry in WalkDir::new(&base).follow_links(false) {
        let entry = entry.map_err(|source| InventoryError::Walk {
            path: base.clone(),
            source,
        })?;
        if !entry.file_type().is_file() || !include(entry.path()) {
            continue;
        }
        let relative = entry
            .path()
            .strip_prefix(root)
            .expect("walked inventory paths are below the repository root");
        let relative = relative
            .to_str()
            .ok_or_else(|| InventoryError::NonUtf8Path(relative.to_path_buf()))?;
        paths.push(relative.replace('\\', "/"));
    }
    paths.sort();
    Ok(paths)
}

fn render_paths(output: &mut String, heading: &str, paths: &[String]) {
    writeln!(output, "## {heading} ({})\n", paths.len()).expect("writing to a string cannot fail");
    if paths.is_empty() {
        writeln!(output, "_None._\n").expect("writing to a string cannot fail");
        return;
    }
    for path in paths {
        writeln!(output, "- `{path}`").expect("writing to a string cannot fail");
    }
    writeln!(output).expect("writing to a string cannot fail");
}
